### ISSUE TITLE
login validation (Check email database)

### ISSUE THREAD

**Issue by Shevonna** [vpaula90/WordGoal#1]
work on login

**Comment by vpaula90** [comment]
I will need to create a validation so that only emails that are on a list can access our site. 

AKA only teachers emails so that parent's cannot login

**Comment by vpaula90** [comment]
https://medium.com/technoetics/handling-user-login-and-registration-using-nodejs-and-mysql-81b146e37419

**Comment by vpaula90** [comment]
https://stackoverflow.com/questions/12759596/validate-email-addresses-in-mysql/12759715

https://dev.mysql.com/doc/mysql-security-excerpt/5.7/en/user-names.html

https://www.daniweb.com/programming/web-development/threads/499321/database-connection-with-html-login

https://gist.github.com/mustafa05deniz/be9d5897267a6ca52e3224e30293b6c3

https://appdividend.com/2017/12/21/simple-nodejs-authentication-system-using-passport/

https://www.inmotionhosting.com/support/website/database-connections/connect-database-remotely-mysql-workbench

**Comment by vpaula90** [comment]
http://www.passportjs.org/

**Comment by vpaula90** [comment]
Had to install "npm install passport"

**Comment by vpaula90** [comment]
https://www.youtube.com/watch?v=6FOq4cUdH8k
